# https://travis-ci.org/PierreRaybaut/formlayout

language: python
sudo: false

env:
  global:
    - MINICONDA_VERSION="latest"
    - MINICONDA_LINUX="Linux-x86_64"
    - MINICONDA_OSX="MacOSX-x86_64"

matrix:
  include:
    - python: "2.7"
      env: USE_QT_API=PyQt4
      os: linux
    - python: "3.4"
      env: USE_QT_API=PyQt4
      os: linux

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export REP_CLONE=$HOME/rep-clone"
  - chmod +x ./continuous_integration/travis/install.sh

install:
  - ./continuous_integration/travis/install.sh;
  - export PATH="$HOME/miniconda/bin:$PATH";

before_script:
 - chmod +x ./continuous_integration/travis/build_test.sh
 - chmod +x ./continuous_integration/travis/main_test.sh

script:
  - ./continuous_integration/travis/build_test.sh
  - ./continuous_integration/travis/main_test.sh
